### PR TITLE
Fixed makefile not working on windows!

### PR DESCRIPTION
**Pull request by Count-MHM**

### CODE REVIEW

**Comment by zorchenhimer** [comment]
The way you've got it will break it on Linux.  The `EXES` variable should really be handled similar the same way `EXT` is handled.  Add the windows version into the if block, and add an else block with the original version.

**Comment by Count-MHM** [comment]
@zorchenhimer
I tested it on Windows 11 and Ubuntu 22.04.2 (with WSL, but this shouldn't really matter), before I submitted the pull request.

On Windows, EXT will first be set to "" then inside the if statement it'll be set to ".exe".
On Linux EXT will first be set to "" and because the if statement fails on Linux it will stay as "".

So on Windows, `$(addsuffix $(EXT), $(addprefix bin/,$(UTILS)))` will add EXT (which is ".exe") to the end of all executables,
and on Linux it'll add EXT (which is "") which doesn't change EXES at all.

You can try it yourself with:
```
git clone "https://github.com/zorchenhimer/go-nes" go-nes-02
git fetch origin pull/1/head:newbranch
git checkout newbranch
```
2023-08-06 12_09_05-Makefile - go-nes-02 - Visual Studio Code

**Comment by Count-MHM** [comment]
Just tested it on "real" Ubuntu 22.04.1:
Screenshot from 2023-08-06 12-19-20

**Comment by zorchenhimer** [comment]
Ah, looks like I've got some egg on my face, lol.  Not sure why I didn't realize that.  Thanks for the followup and the PR!

**Pull request merged**
